# Generated by Django 3.0.1 on 2019-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_name_per_owner'),
        ),
    ]
