# Generated by Django 3.0.1 on 2019-12-29 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191229_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
