# Generated by Django 2.2.5 on 2019-09-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_is_base_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='allowed_categories',
            new_name='categories',
        ),
    ]
