# Generated by Django 2.2.6 on 2019-10-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191005_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Comment'), (1, 'Attachment')])),
                ('comment_content', models.TextField(null=True)),
                ('attachment_content', models.FileField(null=True, upload_to='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
