# Generated by Django 2.2.6 on 2019-10-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191005_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='attachment_content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='comment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
