# Generated by Django 2.2.6 on 2019-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191005_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityentry',
            name='attachment_content',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='type',
        ),
        migrations.AddField(
            model_name='activityentry',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activityentry',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
