# Generated by Django 2.2.6 on 2019-10-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191007_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='attachment_display_name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
    ]
