# Generated by Django 2.2.6 on 2019-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activityentry_attachment_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='attachment_display_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
