# Generated by Django 2.2.6 on 2019-10-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191012_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityentry',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='attachment_display_name',
        ),
    ]
